version: '3.8'

services:
  fastapi:
    image: ghcr.io/juldrixx/docto-technical-case-fastapi:latest
    ports:
      - "8000:8000"
    networks:
      - app-network

  website:
    image: ghcr.io/juldrixx/docto-technical-case-website:latest
    ports:
      - "80:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge