version: '3.8'

services:
  fastapi:
    build:
      context: ./fastapi
    ports:
      - "8000:8000"

  website:
    build:
      context: ./website
    environment:
      - REACT_APP_FASTAPI_URL=http://localhost:8000
      - NGINX_ROOT_PATH=/website
    ports:
      - "80:80"