version: '3.8'

services:
  fastapi:
    build:
      context: ./fastapi
    ports:
      - "8000:8000"
  website:
    build:
      context: ./website
    environment:
      - REACT_APP_FASTAPI_URL=http://localhost:8000
    ports:
      - "80:80"
  db:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - "3406:3306"
    volumes:
      - my-db:/var/lib/mysql

volumes:
  my-db: