name: ci-workflow

on:
  push:
    branches:
      - main

jobs:
  test_fastapi:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12.3"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r fastapi/requirements.txt

      - name: Run tests with coverage
        run: |
          cd fastapi
          coverage run -m pytest
          coverage report
          coverage html
        env:
          TESTING: true

  build_fastapi_image:
    runs-on: ubuntu-latest
    needs: test_fastapi
    if: success()
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Python Docker image
        run: |
          make build-fastapi
          make push-fastapi
    permissions:
      contents: read
      packages: write

  build_website_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push React Docker image
        run: |
          make build-website
          make push-website
    permissions:
      contents: read
      packages: write

  terraform_validate:
    runs-on: ubuntu-latest
    needs: [build_fastapi_image, build_website_image]
    steps:
      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::920373018420:role/github-action
          aws-region: eu-west-3

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.6

      - name: Validate Terraform Configuration
        run: |
          ./terraform.sh \
            --platform aws\
            --env dev \
            --cmd validate
    permissions:
      id-token: write # This is required for requesting the JWT
      contents: read # This is required for actions/checkout
