name: ci-workflow

on:
  push:
    branches:
      - main

jobs:
  test_python:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r fastapi/requirements.txt

      - name: Run tests with coverage
        run: |
          cd fastapi
          coverage run -m pytest
          coverage report
          coverage html
        env:
          TESTING: true

  build_python_image:
    runs-on: ubuntu-latest
    needs: test_python
    if: success()
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Python Docker image
        run: |
          make build-fastapi
          make push-fastapi

  build_react_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push React Docker image
        run: |
          make build-website
          make push-website
